# Module 1

   ### Welcome to the Answer notebook for Module 1 ! 
These notebooks have been provided to code and solve all the queries asked in the modules.

This environment has all the necessary libraries pre-installed, and all the Stock, Commodities and Index data files available at the following location -

#### The problem statements and their corresponding answers are expected to be in the following format -

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------#

### Query 1.1 
Import the csv file of the stock of your choosing using 'pd.read_csv()' function into a dataframe.
Shares of a company can be offered in more than one category. The category of a stock is indicated in the ‘Series’ column. If the csv file has data on more than one category, the ‘Date’ column will have repeating values. To avoid repetitions in the date, remove all the rows where 'Series' column is NOT 'EQ'.
Analyze and understand each column properly.
You'd find the head(), tail() and describe() functions to be immensely useful for exploration. You're free to carry out any other exploration of your own.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import datetime as dt
import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset = pd.read_csv("Small_Cap/JETAIRWAYS.csv")
dataset = dataset[dataset.Series == 'EQ']
dataset

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
0,JETAIRWAYS,EQ,15-May-2017,519.45,520.00,533.40,517.10,527.80,527.50,526.08,1837033,9.664298e+08,25433,430754,23.45
1,JETAIRWAYS,EQ,16-May-2017,527.50,527.00,536.50,524.65,534.00,534.15,531.79,1382182,7.350363e+08,23991,284837,20.61
2,JETAIRWAYS,EQ,17-May-2017,534.15,532.00,534.75,526.20,530.00,528.90,529.75,690466,3.657742e+08,10219,53551,7.76
3,JETAIRWAYS,EQ,18-May-2017,528.90,525.15,538.60,517.50,517.70,522.70,529.55,1701102,9.008102e+08,25651,309608,18.20
4,JETAIRWAYS,EQ,19-May-2017,522.70,525.60,532.90,517.45,521.00,520.40,524.69,1272799,6.678247e+08,20409,257037,20.19
5,JETAIRWAYS,EQ,22-May-2017,520.40,521.70,525.15,469.00,479.50,475.65,491.44,3217513,1.581203e+09,46980,659957,20.51
6,JETAIRWAYS,EQ,23-May-2017,475.65,485.00,489.00,465.30,471.90,472.85,477.05,2924779,1.395252e+09,38240,255332,8.73
7,JETAIRWAYS,EQ,24-May-2017,472.85,473.30,479.90,458.00,466.00,464.80,468.39,2343019,1.097441e+09,37266,402723,17.19
8,JETAIRWAYS,EQ,25-May-2017,464.80,468.10,473.30,459.90,469.70,468.95,467.50,1917412,8.963855e+08,25019,435427,22.71
9,JETAIRWAYS,EQ,26-May-2017,468.95,477.70,491.75,475.10,483.75,483.40,484.19,2668448,1.292045e+09,29370,350943,13.15
10,JETAIRWAYS,EQ,29-May-2017,483.40,481.70,485.35,470.00,476.30,474.60,477.85,949984,4.539516e+08,12123,111663,11.75
11,JETAIRWAYS,EQ,30-May-2017,474.60,471.00,475.05,454.50,458.00,459.65,463.00,1804222,8.353621e+08,23946,259546,14.39
12,JETAIRWAYS,EQ,31-May-2017,459.65,439.00,482.00,438.25,478.65,477.90,466.81,8231445,3.842524e+09,95239,490441,5.96
13,JETAIRWAYS,EQ,01-Jun-2017,477.90,481.00,487.50,467.55,485.00,484.50,477.04,2948808,1.406713e+09,41770,433395,14.70
14,JETAIRWAYS,EQ,02-Jun-2017,484.50,485.00,489.75,478.80,483.80,484.85,484.38,1484965,7.192877e+08,19135,127407,8.58
15,JETAIRWAYS,EQ,05-Jun-2017,484.85,482.00,500.50,479.00,499.85,497.15,490.69,2013452,9.879854e+08,25179,259591,12.89
16,JETAIRWAYS,EQ,06-Jun-2017,497.15,502.50,508.00,493.20,497.70,497.20,500.25,2998048,1.499784e+09,37769,239330,7.98
17,JETAIRWAYS,EQ,07-Jun-2017,497.20,500.80,515.40,496.00,514.55,509.10,504.11,1886376,9.509433e+08,24059,376830,19.98
18,JETAIRWAYS,EQ,08-Jun-2017,509.10,524.00,527.00,516.00,520.00,519.80,521.62,3777232,1.970265e+09,46564,326511,8.64
19,JETAIRWAYS,EQ,09-Jun-2017,519.80,520.90,530.50,514.55,528.70,527.95,523.30,2236841,1.170540e+09,30138,285844,12.78
20,JETAIRWAYS,EQ,12-Jun-2017,527.95,524.00,538.60,524.00,534.80,534.80,533.72,2316549,1.236379e+09,38546,322264,13.91
21,JETAIRWAYS,EQ,13-Jun-2017,534.80,535.10,539.95,528.30,529.10,530.30,534.91,1802366,9.641019e+08,23646,270187,14.99
22,JETAIRWAYS,EQ,14-Jun-2017,530.30,530.20,536.70,525.30,532.90,532.85,530.73,1522657,8.081242e+08,18512,299241,19.65
23,JETAIRWAYS,EQ,15-Jun-2017,532.85,536.80,547.00,532.95,533.50,534.30,540.32,2706366,1.462300e+09,31823,270436,9.99
24,JETAIRWAYS,EQ,16-Jun-2017,534.30,539.45,545.40,536.20,540.00,540.65,541.06,1770157,9.577566e+08,24938,216143,12.21
25,JETAIRWAYS,EQ,19-Jun-2017,540.65,542.00,549.40,541.00,545.70,545.00,545.97,1457930,7.959840e+08,19677,190677,13.08
26,JETAIRWAYS,EQ,20-Jun-2017,545.00,548.20,555.80,545.50,549.00,549.35,550.41,1958913,1.078209e+09,24094,239044,12.20
27,JETAIRWAYS,EQ,21-Jun-2017,549.35,556.00,571.80,553.15,567.00,565.65,564.95,4328418,2.445355e+09,50121,618828,14.30
28,JETAIRWAYS,EQ,22-Jun-2017,565.65,570.80,576.00,565.55,568.00,568.45,572.28,2207590,1.263367e+09,35713,290296,13.15
29,JETAIRWAYS,EQ,23-Jun-2017,568.45,572.00,572.85,549.50,559.95,558.55,560.09,1972589,1.104820e+09,25870,212648,10.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,JETAIRWAYS,EQ,27-Mar-2019,270.90,283.70,287.00,273.75,279.60,276.65,280.11,25539580,7.153822e+09,213854,1903688,7.45
465,JETAIRWAYS,EQ,28-Mar-2019,276.65,274.00,274.00,267.05,270.10,269.20,269.84,10875140,2.934571e+09,90875,970189,8.92
466,JETAIRWAYS,EQ,29-Mar-2019,269.20,275.00,275.80,266.20,267.00,268.80,271.74,6964170,1.892431e+09,59884,701782,10.08
467,JETAIRWAYS,EQ,01-Apr-2019,268.80,268.30,271.45,262.10,266.20,266.10,265.94,8034624,2.136709e+09,69970,585552,7.29
468,JETAIRWAYS,EQ,02-Apr-2019,266.10,267.95,271.10,262.65,264.00,265.00,266.60,4598424,1.225944e+09,40078,454484,9.88
469,JETAIRWAYS,EQ,03-Apr-2019,265.00,256.00,261.40,248.20,251.00,251.75,254.48,12220132,3.109834e+09,101554,885253,7.24
470,JETAIRWAYS,EQ,04-Apr-2019,251.75,245.40,265.20,240.80,261.60,260.30,252.84,21731236,5.494487e+09,188508,984721,4.53
471,JETAIRWAYS,EQ,05-Apr-2019,260.30,260.95,263.30,254.05,255.30,256.10,258.09,10827520,2.794498e+09,85429,712649,6.58
472,JETAIRWAYS,EQ,08-Apr-2019,256.10,255.50,270.30,251.30,262.00,264.25,261.86,17928564,4.694765e+09,157254,1129362,6.30
473,JETAIRWAYS,EQ,09-Apr-2019,264.25,264.50,270.00,261.30,265.20,267.40,266.06,11178219,2.974115e+09,96422,952402,8.52
474,JETAIRWAYS,EQ,10-Apr-2019,267.40,265.20,273.15,258.60,262.25,263.10,266.97,11418980,3.048552e+09,102671,1046540,9.16
475,JETAIRWAYS,EQ,11-Apr-2019,263.10,262.25,268.00,256.00,260.20,261.15,263.53,9627960,2.537276e+09,85317,594130,6.17
476,JETAIRWAYS,EQ,12-Apr-2019,261.15,258.00,265.40,257.00,260.90,260.85,261.04,11373464,2.968973e+09,100969,680683,5.98
477,JETAIRWAYS,EQ,15-Apr-2019,260.85,261.00,264.70,258.20,260.00,261.70,261.31,7175835,1.875082e+09,63488,546010,7.61
478,JETAIRWAYS,EQ,16-Apr-2019,261.70,255.00,257.00,213.20,241.50,240.50,239.07,50984114,1.218876e+10,446289,1822334,3.57
479,JETAIRWAYS,EQ,18-Apr-2019,240.50,216.45,216.45,158.70,165.75,164.85,171.64,56787168,9.747081e+09,539196,5737842,10.10
480,JETAIRWAYS,EQ,22-Apr-2019,164.85,152.00,167.70,126.65,164.85,154.70,145.12,57937856,8.407846e+09,434812,2166653,3.74
481,JETAIRWAYS,EQ,23-Apr-2019,154.70,158.30,174.95,157.50,167.55,169.75,166.67,42707445,7.118074e+09,332333,1780138,4.17
482,JETAIRWAYS,EQ,24-Apr-2019,169.75,171.50,180.00,167.30,170.00,171.15,171.40,18321686,3.140324e+09,157266,1301175,7.10
483,JETAIRWAYS,EQ,25-Apr-2019,171.15,169.40,177.40,162.35,170.00,169.75,169.17,16618898,2.811496e+09,146362,1157138,6.96
484,JETAIRWAYS,EQ,26-Apr-2019,169.75,169.50,173.35,164.50,165.10,167.45,168.88,10793648,1.822824e+09,100935,657047,6.09
485,JETAIRWAYS,EQ,30-Apr-2019,167.45,162.70,162.70,145.10,149.80,153.35,154.93,10010406,1.550942e+09,105686,884579,8.84
486,JETAIRWAYS,EQ,02-May-2019,153.35,138.05,143.00,118.90,135.40,134.25,128.95,34038376,4.389350e+09,282548,1324778,3.89
487,JETAIRWAYS,EQ,03-May-2019,134.25,125.00,138.50,125.00,133.55,135.50,131.50,26924668,3.540583e+09,191140,781515,2.90
488,JETAIRWAYS,EQ,06-May-2019,135.50,125.10,135.80,125.10,129.95,133.40,132.07,14561769,1.923129e+09,104365,581906,4.00
489,JETAIRWAYS,EQ,07-May-2019,133.40,129.70,132.90,121.00,126.00,127.30,128.62,12212871,1.570824e+09,89280,681164,5.58
490,JETAIRWAYS,EQ,08-May-2019,127.30,127.90,136.00,124.15,131.95,131.35,131.47,21943764,2.884869e+09,165672,833160,3.80
491,JETAIRWAYS,EQ,09-May-2019,131.35,133.50,149.30,131.65,147.95,147.40,142.76,34122898,4.871547e+09,223239,1497595,4.39
492,JETAIRWAYS,EQ,10-May-2019,147.40,150.20,157.90,145.30,146.00,151.75,152.92,22274234,3.406187e+09,193811,1431777,6.43
493,JETAIRWAYS,EQ,13-May-2019,151.75,136.60,147.80,134.40,139.00,139.10,142.01,16971715,2.410211e+09,145387,792138,4.67

### Query 1.2
Calculate the maximum, minimum and mean price for the last 90 days. (price=Closing Price unless stated otherwise)

In [3]:
max_price = dataset['Close Price'][len(dataset['Close Price']) - 90 :].max()
min_price = dataset['Close Price'][len(dataset['Close Price']) - 90 :].min()
avg_price = dataset['Close Price'][len(dataset['Close Price']) - 90 :].mean()

print('The Minimum Price for the Jetairways in last 90 days is:% 3.2f\n'
      'The Maximum Price for the Jetairways in last 90 days is:% 3.2f\n' 
      'The Average Price for the Jetairways in last 90 days is:% 3.2f'
      %(min_price, max_price,avg_price))

The Minimum Price for the Jetairways in last 90 days is: 127.30
The Maximum Price for the Jetairways in last 90 days is: 294.45
The Average Price for the Jetairways in last 90 days is: 232.43

### Query 1.3
Analyse the data types for each column of the dataframe. Pandas knows how to deal with dates in an intelligent manner. But to make use of Pandas functionality for dates, you need to ensure that the column is of type 'datetime64(ns)'. Change the date column from 'object' type to 'datetime64(ns)' for future convenience. See what happens if you subtract the minimum value of the date column from the maximum value.

In [4]:
dataset['Date'] = dataset['Date'].astype(dtype = 'datetime64')
dataset['Date'].max() - dataset['Date'].min()

Timedelta('728 days 00:00:00')

### Query 1.4
In a separate array , calculate the monthwise VWAP (Volume Weighted Average Price ) of the stock. 
( VWAP = sum(price*volume)/sum(volume) )

In [5]:
dataset['Year'] = dataset['Date'].dt.year
dataset['Month'] = dataset['Date'].dt.month
dataset['Day'] = dataset['Date'].dt.day

In [6]:
df1 = dataset[['Year','Month','Total Traded Quantity']].groupby(by = ['Month','Year']).sum()
df2 = dataset[['Year','Month','Turnover']].groupby(by = ['Month','Year']).sum()
q = df2['Turnover']/df1['Total Traded Quantity']

In [7]:
print('The monthwise VWAP (Volume Weighted Average Price) is: ')
q

The monthwise VWAP (Volume Weighted Average Price) is:

Month  Year
1      2018    822.669527
       2019    271.173945
2      2018    752.532062
       2019    234.071246
3      2018    680.421115
       2019    251.345263
4      2018    620.666672
       2019    204.080058
5      2017    485.773816
       2018    456.546230
       2019    136.556456
6      2017    533.839322
       2018    383.612206
7      2017    595.578049
       2018    326.720377
8      2017    583.427051
       2018    292.881477
9      2017    545.137806
       2018    233.734160
10     2017    514.835577
       2018    202.554346
11     2017    663.999481
       2018    302.007092
12     2017    728.611391
       2018    267.607376
dtype: float64

### Query 1.5
Write a function to calculate the average price over the last N days of the stock price data where N is a user defined parameter. Write a second function to calculate the profit/loss percentage over the last N days.
Calculate the average price AND the profit/loss percentages over the course of last -
1 week, 2 weeks, 1 month, 3 months, 6 months and 1 year.

In [8]:
def N_day_avg_price(N = 1):
    return dataset['Average Price'][len(dataset) - N:].mean()

In [9]:
def profit_loss_percent(N = 1):
    return (dataset['Close Price'][len(dataset)-1] - dataset['Close Price'][N])/dataset['Close Price'][N]*100

In [10]:
print('The Average Price over last 1 Week is: %3.2f ' %(N_day_avg_price(7)))
print("The Average Price over last 2 Weeks is: %3.2f "  %(N_day_avg_price(14)))
print("The Average Price over last 1 Month is: %3.2f "  %(N_day_avg_price(30)))
print("The Average Price over last 6 Months is: %3.2f " %(N_day_avg_price(30*6)))
print("The Average Price over last year is: %3.2f "  %(N_day_avg_price(365)))

The Average Price over last 1 Week is: 137.34
The Average Price over last 2 Weeks is: 147.61
The Average Price over last 1 Month is: 205.92
The Average Price over last 6 Months is: 243.74
The Average Price over last year is: 414.89

In [11]:
print('The Profit/Loss percentage over last 1 Week is: %3.2f ' %(profit_loss_percent(7)))
print("The Profit/Loss percentage over last 2 Weeks is: %3.2f "  %(profit_loss_percent(14)))
print("The Profit/Loss percentage over last 1 Month is: %3.2f "  %(profit_loss_percent(30)))
print("The Profit/Loss percentage over last 6 Months is: %3.2f " %(profit_loss_percent(30*6)))
print("The Profit/Loss percentage over last year is: %3.2f "  %(profit_loss_percent(365)))

The Profit/Loss percentage over last 1 Week is: -70.07
The Profit/Loss percentage over last 2 Weeks is: -71.31
The Profit/Loss percentage over last 1 Month is: -74.81
The Profit/Loss percentage over last 6 Months is: -81.54
The Profit/Loss percentage over last year is: -38.07

### Query 1.6
Add a column 'Day_Perc_Change' where the values are the daily change in percentages i.e. the percentage change between 2 consecutive day's closing prices. Instead of using the basic mathematical formula for computing the same, use 'pct_change()' function provided by Pandas for dataframes. You will note that the first entry of the column will have a ‘Nan’ value. Why does this happen? Either remove the first row, or set the entry to 0 before proceeding.

In [12]:
dataset['Day_Prec_Change'] = dataset['Close Price'].pct_change()*100
dataset['Day_Prec_Change'][0] = 0.000

### Query 1.7
Add another column 'Trend' whose values are: <br>
* 'Slight or No change' for 'Day_Perc_Change' in between -0.5 and 0.5<br>
* 'Slight positive' for 'Day_Perc_Change' in between 0.5 and 1<br>
* 'Slight negative' for 'Day_Perc_Change' in between -0.5 and -1<br>
* 'Positive' for 'Day_Perc_Change' in between 1 and 3<br>
* 'Negative' for 'Day_Perc_Change' in between -1 and -3<br>
* 'Among top gainers' for 'Day_Perc_Change' in between 3 and 7<br>
* 'Among top losers' for 'Day_Perc_Change' in between -3 and -7<br>
* 'Bull run' for 'Day_Perc_Change' >7<br>
* 'Bear drop' for 'Day_Perc_Change' <-7<br>

In [13]:
dataset['Trend'] = np.nan
for i in range(len(dataset)):
    if dataset['Day_Prec_Change'][i] > -0.5 and dataset['Day_Prec_Change'][i] < 0.5:
        dataset['Trend'][i] = 'Slight or No Change'
    elif dataset['Day_Prec_Change'][i] > 0.5 and dataset['Day_Prec_Change'][i] < 1:
        dataset['Trend'][i] = 'Slight positive'
    elif dataset['Day_Prec_Change'][i] > 1 and dataset['Day_Prec_Change'][i] < 3:
        dataset['Trend'][i] = 'Positive'
    elif dataset['Day_Prec_Change'][i] > 3 and dataset['Day_Prec_Change'][i] < 7:
        dataset['Trend'][i] = 'Among top gainers'
    elif dataset['Day_Prec_Change'][i] > 7:
        dataset['Trend'][i] = 'Bull run'
    elif dataset['Day_Prec_Change'][i] > -1 and dataset['Day_Prec_Change'][i] < -0.5:
        dataset['Trend'][i] = 'Slight negative'
    elif dataset['Day_Prec_Change'][i] > -3 and dataset['Day_Prec_Change'][i] < -1:
        dataset['Trend'][i] = 'Negative'
    elif dataset['Day_Prec_Change'][i] > -7 and dataset['Day_Prec_Change'][i] < -3:
        dataset['Trend'][i] = 'Among top losers'
    elif dataset['Day_Prec_Change'][i] < -7:
        dataset['Trend'][i] = 'Bear run'

### Query 1.8
Find the average and median values of the column 'Total Traded Quantity' for each of the types of 'Trend'.

In [46]:
print('The Average of the Total Traded Quantity grouped by Trend is:')
dataset[['Trend','Total Traded Quantity']].groupby(by = ['Trend']).mean()

The Average of the Total Traded Quantity grouped by Trend is:

                     Total Traded Quantity
Trend
Among top gainers             9.826436e+06
Among top losers              8.110081e+06
Bear run                      1.773643e+07
Bull run                      2.649510e+07
Negative                      4.997933e+06
Positive                      5.840309e+06
Slight negative               3.890615e+06
Slight or No Change           4.627527e+06
Slight positive               4.822245e+06

In [47]:
print('The Median of the Total Traded Quantity grouped by Trend is:')
dataset[['Trend','Total Traded Quantity']].groupby(by = ['Trend']).median()

The Median of the Total Traded Quantity grouped by Trend is:

                     Total Traded Quantity
Trend
Among top gainers                5878245.0
Among top losers                 5545462.0
Bear run                        10010406.0
Bull run                        14275940.5
Negative                         3572065.0
Positive                         3713022.0
Slight negative                  2575455.0
Slight or No Change              2879975.0
Slight positive                  3227703.0

### Query 1.9
SAVE the dataframe with the additional columns computed as a csv file week2.csv. In Module 2, you are going to get familiar with matplotlib, the python module which is used to visualize data.

In [49]:
export_csv = dataset.to_csv (r'week2.csv', index = None, header=True)